### ISSUE TITLE
Fix 3+ split layout

### ISSUE THREAD

**Issue by nathancahill** [nathancahill/Split.js#1]
Because of a float division or rounding error, when splitting in 3 or more panes, the total width is too wide and the last pane falls off.

**Comment by RodMontgomery** [comment]
It's not due to either float division or rounding error. It's due to the code being written as if the percentages for the two panes whose boundary is being moved add to 100%. If there are more than two panes, this is not true.

I have a fixed version, for which I will submit a pull request as soon as I figure out how. (GitHub newbie here.)

I also have a transposition into the key of vertical splits, which I will also include in my pull request.

**Comment by nathancahill** [comment]
Awesome! Excited to check it out :)

**Comment by RodMontgomery** [comment]
Still trying to wrap my brain around GitHub. Submitted one pull request just to fix the recalc-on-drag. Will do the vertical splits separately.

**Comment by nathancahill** [comment]
Check this out @RodMontgomery. Wrapped my head around the >2 case. Both the first and the last gutters should be `guttterWidth / 2`. Then, to calculate the widths of pairs of elements, use the pairs initial width percentage of parent (instead of 100%).
