### ISSUE TITLE
New option: Local storage

### ISSUE THREAD

**Issue by efureev** [nathancahill/Split.js#22]
Remember last state in Local Storage =)

**Comment by nathancahill** [comment]
Maybe. I'll think on it. Might be something that should be implemented by the user with the callbacks.

**Comment by PAEz** [comment]
For the user to implement save they kinda need some info on the drag events and this requires changing split.js
I did it here (plus all my other recent changes).
http://plnkr.co/edit/Q0dvKbmQJ3CFrcV4q58M?p=preview
Put a limiter on the drag saving, using requestAnimationFrame.
And since I was throwing em round put one on adjust in split.js aswell.
The drag event can fire like nuts, this stops dom thrashing.
Prolly wnna check its ok i guess.
Got a problem of a flick on load, wonder if its partly that, could add a force optoin to adjust only need it at the beginning.

**Comment by nathancahill** [comment]
This can be done using the new APIs in v1.2.0:

```js
var sizes = localStorage.getItem('split-sizes') || [50, 50]

var split = Split(sizes, {
    onDragEnd: function () {
        localStorage.setItem('split-sizes', split.getSizes());
    }
})
```

**Comment by Surt** [comment]
I'm having problems triying to access the sizes for saving.

`localStorage.setItem('split-sizes', split.getSizes());`
split.getSizes() is undefined
