### ISSUE TITLE
Zoom breaks Split.js on Chrome, Firefox

### ISSUE THREAD

**Issue by guilhermesimoes** [nathancahill/Split.js#23]
![splitjs](https://cloud.githubusercontent.com/assets/531168/11629372/c8bb6840-9cef-11e5-8233-8b8164c8f0a4.gif)

**Comment by nathancahill** [comment]
Excellent, thanks for the bug report. I'll take a look at this.

**Comment by PAEz** [comment]
Do you notice that problem with this version?........
http://embed.plnkr.co/9gAv6U4sRaWt6Oeljrrf/

**Comment by guilhermesimoes** [comment]
Everything works fine! But I'm not sure if your example is set up exactly the same way as the Split.js website.

**Comment by PAEz** [comment]
Cool!  Think it was the percentage problem, all fixed now (plus a few other things).
Pretty much, turned off snap, css is wrong, mins changed, but in essence its the same.
Now we just wait and see what nathancahill thinks of it ;P

**Comment by Khorkhe** [comment]
Another case of this would be:

- Cmd + (zoom) the page
- Force refresh: Cmd Shift R (the page refreshes while still being zoomed)
- Reset zoom to 100%: Cmd 0 (zero).

The body that used to fill 100% of vertical space now only fills a portion of that.  In the screenshot below, the vertical grip image is still visible where it is supposed to be, but the quadrants are shrunk.

It seems body height needs to be refreshed.  Any ideas?
Otherwise, thanks for a great module!

![image](https://cloud.githubusercontent.com/assets/4688418/14400287/8653d750-fdaa-11e5-8d39-47f97e4adb42.png)

**Comment by nathancahill** [comment]
This is fixed in v1.2.0.
