### ISSUE TITLE
minSize is ignored if initial sizes evaluate to a smaller size

### ISSUE THREAD

**Issue by rroels** [nathancahill/Split.js#72]
I found that when the "sizes" properties are set up so that they break the "minSize" requirements from the start, the minSize requirements will never be respected. 

As an (extreme) example: 
```
Split(['#panel_left', '#panel_right'], {
        sizes: [1, 99],
        minSize: [300, 300],
        gutterSize: 8,
        cursor: 'col-resize'
});
```
If 1% width for the left panel is smaller than 300px, the minSize of 300px will never be respected, also not after manually making it bigger than 300px.

This is causing some annoyances for me because a sensible split like [20, 80] works fine on a wide screen, but on a smaller monitor the left bar is so small the content doesn't fit and messes everything up. I would love to be able to say "20% but if that's less than the minSize, use the minSize instead".  

I found that using CSS values like this achieves what I want to do:
`sizes: ['300px', 'calc(100% - 310px)']`

However, it's not very practical as you have to take the gutter's width into account and hardcode a lot of values (or do some calculations in JavaScript). Also the documentation advises against using CSS values. 

Is this intended behaviour, or perhaps something that could be addressed in future releases?

**Comment by jakeb16** [comment]
Thanks for the tip, that definitely helped me.

**Comment by nathancahill** [comment]
I see the issue here. I'll switch it to respect minSize (update the initial size to minSize), since it's more likely that a set pixel value would be needed for a view. I think it will be a breaking change though, in case people currently rely on the previous behavior.

**Comment by nathancahill** [comment]
The real issue with updating the size is that the minimum size could be greater than the next view, in which case, the size change would have to cascade through each view, pushing each one further, or max out at fully closed.

**Comment by pesla** [comment]
I have the exact same issue, so just chiming in.

**Comment by nathancahill** [comment]
I'm open to suggestions on how to handle the case above.

**Comment by nathancahill** [comment]
Here's a tentative fix. Please give it a try if you can: https://github.com/nathancahill/Split.js/blob/fixes/respect-min/split.js

This solves the problem above by pushing all elements except the last. This might not be desirable, if the last element is the one that is constrained. Maybe there could be a "adjust: forward" or "adjust: backward" option for the user to specify.

**Comment by pesla** [comment]
@nathancahill Works like a charm for me.

Can you elaborate on your previous comment on what the real issue is?

I would expect `Split.js` to be unopinionated in regard to handling properties like `minSize` (or `maxSize` if that would be implemented). In the same way CSS handles `min-width` and `max-width`. It doesn't worry about wether or not the layout would break, that's up to the implementor. 

For example, see the following fiddle: https://jsfiddle.net/ya394u7p/2/. It showcases that:

* `min-width` takes precedence over `max-width`
* CSS doesn't try to fix a development error (eg. layout will break if the implementor has set conflicting values)

If a developer sets split panes up using conflicting values, it'll show quick enough for him to fix it, in the same way he'd been mistaken using plain CSS. Split panes are used for specific use cases, which I assume require some attention to detail while implementing them.

A side effect of choosing this direction would be that you could get rid of any complexity related to fixing sizes. The size of a pane could be determined as following (simplified):

```js
let size = element.getBoundingClientRect()[dimension];

if (size <= minSize) {
    return minSize;
}

if (size >= maxSize) {
    return maxSize;
}

return setElementSize(dimension, size);
```

I might be oversimplifying things. What do you think?

**Comment by nathancahill** [comment]
This is possible with the new `expandToMin` option in v1.5.0.
