### ISSUE TITLE
Mobile friendly views?

### ISSUE THREAD

**Issue by minutephp-plugins** [nathancahill/Split.js#80]
Is there a way to make it work with mobile phones? 

So the split view is automatically shows side-by-side on desktop but changes to top-by-bottom on a mobile phone?

Kind of like how the "col-sm-" classes work in Bootstrap.

Any suggestions?

Thanks

**Comment by nathancahill** [comment]
You'd have to do the screen size detection yourself, and then create either a vertical split or a horizontal split.

**Comment by slidenerd** [comment]
Would be great, if you can put up a simple example of how to go about that, thank you for everything

**Comment by slidenerd** [comment]
Ok i gave it a shot @minutephp-plugins , as hacky as [THIS ](https://codepen.io/zupkode/pen/VrJYxq)is, it works I tried the normal route. the problem is that we need to listen to the viewport reisizing with the help of onresize and then if the window.innerWidth < 768 for example we trigger split with vertical layout else horizontal layout. Only 1 issue in this simple logic is that the library keeps adding gutters as it resizes inside the onResize method. @nathancahill a better solution is super appreciated

**Comment by slidenerd** [comment]
Done, there you go @minutephp-plugins [THIS ](https://codepen.io/zupkode/pen/POrNap) should match your needs. The trick here is to keep the split variable outside the function resize so that everytime we resize the window and the function is called, we destroy the split instance and create it once again to avoid adding gutters, you can try removing the if(split){split.destroy()} statement or keep the variable inside the function, resize the window and see the effect for yourself

**Comment by oraclei** [comment]
Hi slidenerd, I have the same problem, but  "@minutephp-plugins THIS" link was not found, Can you give me a reference link ? thanks a lot.

**Comment by yemling** [comment]
@slidenerd I could really do with seeing your example too. I thought I'd sorted the issue myself doing what you suggested but intermittently get this error:

> split.js:734 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at http://localhost:81/lib/split.js:734:33
    at Array.forEach (<anonymous>)
    at Object.destroy (http://localhost:81/lib/split.js:731:19)
