### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive

### ISSUE THREAD

**Issue by baev** [nathancahill/Split.js#97]
at split.js:444

Not sure is it necessary to use blocking `touchstart` event or not

**Comment by davidje13** [comment]
There are 2 places where this happens:

`touchmove`: this can simply be marked as passive with `{passive: true}` when registered (plus necessary legacy browser support). The callback never uses `preventDefault`.

`touchstart`: the registered callback uses `preventDefault` both to avoid selection artefacts (when called from `mousedown`) and prevent scrolling (when called from `touchstart`). Since the whole "make the page more responsive" warning is about improving scroll performance, and scrolling is being blocked intentionally, it's somewhat irrelevant. It would be nice if the warning could be silenced somehow, but this is a valid use of a non-passive event listener.

**Comment by nathancahill** [comment]
Thanks for the explanation!

**Comment by bliitzkrieg** [comment]
Anyone know how to resolve this warning for the react-split library?

**Comment by Reverier-Xu** [comment]
for guys who found here:  this is just a warning not panic so you can ignore it...

If you have to remove this warning for some reason. try [this library](https://www.npmjs.com/package/passive-events-support)

```ts
  import { passiveSupport } from 'passive-events-support/src/utils'
  passiveSupport({
    events: ['touchstart'],
    listeners: [
      {
        element: 'gutter',
        event: 'touchstart',
        prevented: true,
      },
    ],
  })
  import Split from 'split.js'

  ...

  Split([...], {
    ...
    gutter: (_index, _direction) => {
        const gutter = document.createElement('div')
        gutter.className = `gutter ...`
        return gutter
      }
  })
```
